FROM python:3.7-alpine
MAINTAINER Mike Ryan "mikeryan56@gmail.com"
EXPOSE 5000
ENV VIRTUAL_HOST quart-sufee.devsetgo.com
ENV LETSENCRYPT_HOST quart-sufee.devsetgo.com
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
CMD ["gunicorn", "-c", "gunicorn_cfg.py", "sufee:app"]